In [1]:
import pandas as pd
import numpy as np
import vaex

In [2]:
#read TRAF with vaex

traf = vaex.open('TRAFICO/TRAF.hdf5')

[03/14/23 13:49:05] ERROR    error opening 'TRAFICO/TRAF.hdf5'                                      ]8;id=236391;file://c:\Users\calba\anaconda3\lib\site-packages\vaex\__init__.py\__init__.py]8;;\:]8;id=744654;file://c:\Users\calba\anaconda3\lib\site-packages\vaex\__init__.py#271\271]8;;\
                             Traceback (most recent call last):
                               File "c:\Users\calba\anaconda3\lib\site-packages\vaex\__init__.py",
                             line 244, in open
                                 ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs,
                             **kwargs)
                               File "c:\Users\calba\anaconda3\lib\site-packages\vaex\dataset.py",
                             line 80, in open
                                 if opener.can_open(path, fs_options=fs_options, fs=fs, *args,
                             **kwargs):
                               File
                             "c:\Users\calba\anaconda3\lib\site-packages\vaex\hdf5\dataset.py",
                             line 167, in can_open
                                 with vaex.file.open(path, fs_options=fs_options, fs=fs) as f:
                               File
                             "c:\Users\calba\anaconda3\lib\site-packages\vaex\file\__init__.py",
                             line 320, in open
                                 return normal_open(path, mode)
                             FileNotFoundError: [Errno 2] No such file or directory:
                             'TRAFICO/TRAF.hdf5'

FileNotFoundError: [Errno 2] No such file or directory: 'TRAFICO/TRAF.hdf5'

In [ ]:
traf

#            idelem    fecha                intensidad    ocupacion    carga
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0
...          ...       ...                  ...           ...          ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0

In [3]:
#read geo_live

geo_loc = pd.read_csv('TRAFICO/geo_loc.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'TRAFICO/geo_loc.csv'

In [4]:
geo_loc

NameError: name 'geo_loc' is not defined

In [15]:
#change name from id to idelem

geo_loc.rename(columns={'id':'idelem'}, inplace=True)

geo_loc = geo_loc[['idelem','station']]

geo_loc

      idelem station
0       3840    3195
1       3841    3195
2       3842    3195
3       3843    3195
4       3844    3195
...      ...     ...
4685    6809   3194U
4686    6810   3194U
4687    6933   3194U
4688    7129   3194U
4689    7015   3194U

[4690 rows x 2 columns]

In [6]:
#read meteo

meteo = pd.read_csv('../data/meteo.csv')

meteo = meteo[['fecha','station','prec','velmedia']]

In [7]:
meteo

            fecha station prec velmedia
0      2013-01-01    3200  0,0      1,7
1      2013-01-01    3129  0,0      1,4
2      2013-01-01   3194U  0,4      0,3
3      2013-01-01    3196  0,0      1,1
4      2013-01-01    3195  0,0      1,1
...           ...     ...  ...      ...
18161  2022-12-31    3200  0,0      1,7
18162  2022-12-31    3129  0,0      1,9
18163  2022-12-31   3194U  0,1      0,3
18164  2022-12-31    3196  0,3      1,1
18165  2022-12-31    3195  0,0      0,8

[18166 rows x 4 columns]

In [8]:
#geo_loc to vaex

geo_loc_vaex = vaex.from_pandas(geo_loc)

NameError: name 'geo_loc' is not defined

In [18]:
#join traf and geo_loc

traf_geo = traf.join(geo_loc_vaex, on='idelem', how='left')

traf_geo

#            idelem    fecha                intensidad    ocupacion    carga    station
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0      3195
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0     3195
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0     3195
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0     3195
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0     3195
...          ...       ...                  ...           ...          ...      ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0      3194U
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0      3194U
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0      3194U
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0      3194U
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0      3194U

In [25]:
#take first 10 characters from fecha

traf_geo['fecha2'] = traf_geo['fecha'].str.slice(0,10)

In [33]:
#rename fecha as fecha_full

traf_geo.rename('fecha','fecha_full')

'fecha_full'

In [34]:
traf_geo

#            idelem    fecha_full           intensidad    ocupacion    carga    station    fecha2
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0      3195       2013-01-20
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0     3195       2013-01-20
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0     3195       2013-01-20
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0     3195       2013-01-20
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0     3195       2013-01-20
...          ...       ...                  ...           ...          ...      ...        ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0      3194U      2022-12-31
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0      3194U      2022-12-31
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0      3194U      2022-12-31
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0      3194U      2022-12-31
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0      3194U      2022-12-31

In [35]:

traf_geo.rename('fecha2','fecha')

'fecha'

In [36]:
traf_geo

#            idelem    fecha_full           intensidad    ocupacion    carga    station    fecha
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0      3195       2013-01-20
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0     3195       2013-01-20
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0     3195       2013-01-20
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0     3195       2013-01-20
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0     3195       2013-01-20
...          ...       ...                  ...           ...          ...      ...        ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0      3194U      2022-12-31
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0      3194U      2022-12-31
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0      3194U      2022-12-31
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0      3194U      2022-12-31
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0      3194U      2022-12-31

In [69]:
#drop duplicates from meteo

meteo = meteo.drop_duplicates()

meteo

            fecha station prec velmedia
0      2013-01-01    3200  0,0      1,7
1      2013-01-01    3129  0,0      1,4
2      2013-01-01   3194U  0,4      0,3
3      2013-01-01    3196  0,0      1,1
4      2013-01-01    3195  0,0      1,1
...           ...     ...  ...      ...
18161  2022-12-31    3200  0,0      1,7
18162  2022-12-31    3129  0,0      1,9
18163  2022-12-31   3194U  0,1      0,3
18164  2022-12-31    3196  0,3      1,1
18165  2022-12-31    3195  0,0      0,8

[17591 rows x 4 columns]

In [70]:
#make meteo vaex

meteo_vaex = vaex.from_pandas(meteo)
meteo_vaex

#       fecha       station    prec    velmedia
0       2013-01-01  3200       0,0     1,7
1       2013-01-01  3129       0,0     1,4
2       2013-01-01  3194U      0,4     0,3
3       2013-01-01  3196       0,0     1,1
4       2013-01-01  3195       0,0     1,1
...     ...         ...        ...     ...
17,586  2022-12-31  3200       0,0     1,7
17,587  2022-12-31  3129       0,0     1,9
17,588  2022-12-31  3194U      0,1     0,3
17,589  2022-12-31  3196       0,3     1,1
17,590  2022-12-31  3195       0,0     0,8

In [71]:
meteo_vaex['joinear'] = meteo_vaex['fecha'] + ' ' + meteo_vaex['station']

meteo_vaex

#       fecha       station    prec    velmedia    joinear
0       2013-01-01  3200       0,0     1,7         2013-01-01 3200
1       2013-01-01  3129       0,0     1,4         2013-01-01 3129
2       2013-01-01  3194U      0,4     0,3         2013-01-01 3194U
3       2013-01-01  3196       0,0     1,1         2013-01-01 3196
4       2013-01-01  3195       0,0     1,1         2013-01-01 3195
...     ...         ...        ...     ...         ...
17,586  2022-12-31  3200       0,0     1,7         2022-12-31 3200
17,587  2022-12-31  3129       0,0     1,9         2022-12-31 3129
17,588  2022-12-31  3194U      0,1     0,3         2022-12-31 3194U
17,589  2022-12-31  3196       0,3     1,1         2022-12-31 3196
17,590  2022-12-31  3195       0,0     0,8         2022-12-31 3195

In [72]:
meteo_vaex['joinear'].value_counts()

2017-05-22 3194U    1
2021-10-22 3200     1
2021-10-06 3195     1
2015-05-27 3129     1
2014-10-22 3194U    1
                   ..
2013-07-14 3196     1
2020-07-27 3194U    1
2021-02-16 3129     1
2020-11-14 3194U    1
2019-01-29 3196     1
Length: 17591, dtype: int64

In [48]:
traf_geo['joinear'] = traf_geo['fecha'] + ' ' + traf_geo['station']

traf_geo

#            idelem    fecha_full           intensidad    ocupacion    carga    station    fecha       joinear
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0      3195       2013-01-20  2013-01-20 3195
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0     3195       2013-01-20  2013-01-20 3195
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0     3195       2013-01-20  2013-01-20 3195
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0     3195       2013-01-20  2013-01-20 3195
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0     3195       2013-01-20  2013-01-20 3195
...          ...       ...                  ...           ...          ...      ...        ...         ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0      3194U      2022-12-31  2022-12-31 3194U
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0      3194U      2022-12-31  2022-12-31 3194U
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0      3194U      2022-12-31  2022-12-31 3194U
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0      3194U      2022-12-31  2022-12-31 3194U
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0      3194U      2022-12-31  2022-12-31 3194U

In [73]:
#join traf_geo and meteo by fecha and station

traf_geo_meteo = traf_geo.join(meteo_vaex, on='joinear', how='left', lsuffix='_left', rsuffix='_right')

In [74]:
traf_geo_meteo

#            idelem    fecha_full           intensidad    ocupacion    carga    station_left    fecha_left    joinear_left      fecha_right    station_right    prec    velmedia    joinear_right
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0      3195            2013-01-20    2013-01-20 3195   2013-01-20     3195             0,7     3,3         2013-01-20 3195
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0     3195            2013-01-20    2013-01-20 3195   2013-01-20     3195             0,7     3,3         2013-01-20 3195
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0     3195            2013-01-20    2013-01-20 3195   2013-01-20     3195             0,7     3,3         2013-01-20 3195
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0     3195            2013-01-20    2013-01-20 3195   2013-01-20     3195             0,7     3,3         2013-01-20 3195
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0     3195            2013-01-20    2013-01-20 3195   2013-01-20     3195             0,7     3,3         2013-01-20 3195
...          ...       ...                  ...           ...          ...      ...             ...           ...               ...            ...              ...     ...         ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0      3194U           2022-12-31    2022-12-31 3194U  2022-12-31     3194U            0,1     0,3         2022-12-31 3194U
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0      3194U           2022-12-31    2022-12-31 3194U  2022-12-31     3194U            0,1     0,3         2022-12-31 3194U
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0      3194U           2022-12-31    2022-12-31 3194U  2022-12-31     3194U            0,1     0,3         2022-12-31 3194U
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0      3194U           2022-12-31    2022-12-31 3194U  2022-12-31     3194U            0,1     0,3         2022-12-31 3194U
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0      3194U           2022-12-31    2022-12-31 3194U  2022-12-31     3194U            0,1     0,3         2022-12-31 3194U

In [76]:
#drop columns station_left and station_right, joinear_left and joinear_right and fecha_left and fecha_right

traf_geo_meteo = traf_geo_meteo.drop(['station_left','station_right','joinear_left','joinear_right','fecha_left','fecha_right'])

In [77]:
traf_geo_meteo

#            idelem    fecha_full           intensidad    ocupacion    carga    prec    velmedia
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0      0,7     3,3
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0     0,7     3,3
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0     0,7     3,3
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0     0,7     3,3
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0     0,7     3,3
...          ...       ...                  ...           ...          ...      ...     ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0      0,1     0,3
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0      0,1     0,3
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0      0,1     0,3
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0      0,1     0,3
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0      0,1     0,3

In [87]:
#save to hdf5

traf_geo_meteo.export_hdf5('TRAFICO/traf_hist.hdf5')

In [2]:
import vaex
import sqlalchemy as db

# create a connection to the SQL database using SQLAlchemy
engine = db.create_engine('mysql+pymysql://root:Qwqw1212_@127.0.0.1:3306/proyecto_acci')

In [89]:
engine

Engine(mysql+pymysql://root:***@127.0.0.1:3306/proyecto_acci)

In [1]:
import pandas as pd
import numpy as np
import vaex

In [2]:
#read accidentalidad

acci = pd.read_csv('../data/accidentalidad.csv')

acci

,fecha,station,tmed,prec,velmedia,hora,distrito,localizacion,id,coordenada_x_utm,coordenada_y_utm,lesividad,meteo,latitud,longitud
0,2013-01-01,3129,"5,6","0,0","1,4",19:00,SAN BLAS,GLORIETA DE ARCENTALES - AUTOVIA M-40,6404.0,448272.810572,4.476161e+06,HL,Normal,40.434484,-3.609872
1,2013-01-01,3194U,"5,6","0,4","0,3",00:00,FUENCARRAL-EL PARDO,"AUTOVIA M-30 CALZADA 1 KM., 31400",4608.0,442092.763289,4.481385e+06,HL,Lloviendo,40.481134,-3.683207
2,2013-01-01,3194U,"5,6","0,4","0,3",00:00,TETUAN,AVENIDA DE ASTURIAS - CALLE DEL CAÑAVERAL,4579.0,441163.603568,4.479990e+06,HL,Lloviendo,40.468500,-3.694040
3,2013-01-01,3194U,"5,6","0,4","0,3",13:00,MONCLOA-ARAVACA,"AVENIDA DEL DOCTOR FEDERICO RUBIO Y GALI, 65",4516.0,439401.879502,4.478458e+06,HL,Normal,40.454575,-3.714673
4,2013-01-01,3194U,"5,6","0,4","0,3",17:00,TETUAN,"CALLE DE LOPE DE HARO, 8",5632.0,440446.435648,4.478757e+06,HL,Normal,40.457344,-3.702383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122134,2022-12-31,3195,"8,9","0,0","0,8",5:00,SAN BLAS-CANILLEJAS,"CALLE TAMPICO, 16",10554.0,446310.000000,4.476975e+06,NO ASIGNADA,Normal,40.440179,-3.632464
122135,2022-12-31,3195,"8,9","0,0","0,8",6:00,PUENTE DE VALLECAS,"AVDA. ALBUFERA, 246",6947.0,445162.000000,4.471242e+06,HL,Normal,40.389891,-3.645091
122136,2022-12-31,3195,"8,9","0,0","0,8",6:00,SALAMANCA,"C/ JOSE ORTEGA Y GASSET, 40-42",4006.0,442441.000000,4.475706e+06,NO ASIGNADA,Normal,40.429990,-3.677839
122137,2022-12-31,3195,"8,9","0,0","0,8",6:30,VILLA DE VALLECAS,"CALLE ENRIQUE GARCIA ALVAREZ, 11",10785.0,447813.000000,4.470373e+06,NO ASIGNADA,Normal,40.382550,-3.610817
122138,2022-12-31,3195,"8,9","0,0","0,8",8:30,MORATALAZ,"CMNO. ANTIGUO VIEJO DE VICALVARO, FAROLA 172",6212.0,447542.000000,4.472949e+06,MT,Normal,40.405273,-3.616231

In [3]:
acci = acci[['fecha', 'hora', 'id']]

In [4]:
acci['accidente'] = 1

acci

C:\Users\calba\AppData\Local\Temp\ipykernel_22912\3559154870.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acci['accidente'] = 1

             fecha   hora       id  accidente
0       2013-01-01  19:00   6404.0          1
1       2013-01-01  00:00   4608.0          1
2       2013-01-01  00:00   4579.0          1
3       2013-01-01  13:00   4516.0          1
4       2013-01-01  17:00   5632.0          1
...            ...    ...      ...        ...
122134  2022-12-31   5:00  10554.0          1
122135  2022-12-31   6:00   6947.0          1
122136  2022-12-31   6:00   4006.0          1
122137  2022-12-31   6:30  10785.0          1
122138  2022-12-31   8:30   6212.0          1

[122139 rows x 4 columns]

In [5]:
acci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122139 entries, 0 to 122138
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   fecha      122139 non-null  object
 1   hora       122139 non-null  object
 2   id         122139 non-null  float64
 3   accidente  122139 non-null  int64
dtypes: float64(1), int64(1), object(2)
memory usage: 3.7+ MB

In [6]:
#acci id to object

acci['id'] = acci['id'].astype('string')

acci.info()

C:\Users\calba\AppData\Local\Temp\ipykernel_22912\650044012.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acci['id'] = acci['id'].astype('string')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122139 entries, 0 to 122138
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   fecha      122139 non-null  object
 1   hora       122139 non-null  object
 2   id         122139 non-null  string
 3   accidente  122139 non-null  int64
dtypes: int64(1), object(2), string(1)
memory usage: 3.7+ MB

In [7]:
#get rid of the last 2 characters from id

acci['id'] = acci['id'].str.slice(0, -2)

acci

C:\Users\calba\AppData\Local\Temp\ipykernel_22912\2620456417.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acci['id'] = acci['id'].str.slice(0, -2)

             fecha   hora     id  accidente
0       2013-01-01  19:00   6404          1
1       2013-01-01  00:00   4608          1
2       2013-01-01  00:00   4579          1
3       2013-01-01  13:00   4516          1
4       2013-01-01  17:00   5632          1
...            ...    ...    ...        ...
122134  2022-12-31   5:00  10554          1
122135  2022-12-31   6:00   6947          1
122136  2022-12-31   6:00   4006          1
122137  2022-12-31   6:30  10785          1
122138  2022-12-31   8:30   6212          1

[122139 rows x 4 columns]

In [8]:
#add 0 to the left of hora if length is 4

for i in range(len(acci)):
    if len(acci['hora'][i]) == 4:
        acci['hora'][i] = '0' + acci['hora'][i]

acci

C:\Users\calba\AppData\Local\Temp\ipykernel_22912\3425181217.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acci['hora'][i] = '0' + acci['hora'][i]

             fecha   hora     id  accidente
0       2013-01-01  19:00   6404          1
1       2013-01-01  00:00   4608          1
2       2013-01-01  00:00   4579          1
3       2013-01-01  13:00   4516          1
4       2013-01-01  17:00   5632          1
...            ...    ...    ...        ...
122134  2022-12-31  05:00  10554          1
122135  2022-12-31  06:00   6947          1
122136  2022-12-31  06:00   4006          1
122137  2022-12-31  06:30  10785          1
122138  2022-12-31  08:30   6212          1

[122139 rows x 4 columns]

In [9]:
#acci to vaex

acci_vaex = vaex.from_pandas(acci)

acci_vaex

#        fecha       hora    id     accidente
0        2013-01-01  19:00   6404   1
1        2013-01-01  00:00   4608   1
2        2013-01-01  00:00   4579   1
3        2013-01-01  13:00   4516   1
4        2013-01-01  17:00   5632   1
...      ...         ...     ...    ...
122,134  2022-12-31  05:00   10554  1
122,135  2022-12-31  06:00   6947   1
122,136  2022-12-31  06:00   4006   1
122,137  2022-12-31  06:30   10785  1
122,138  2022-12-31  08:30   6212   1

In [10]:
acci_vaex['unir'] = acci_vaex['fecha'] + ' ' + acci_vaex['hora'] + ':00' + ' ' + acci_vaex['id']

In [11]:
acci_vaex = acci_vaex.drop(['fecha','hora','id'])

acci_vaex

#        accidente    unir
0        1            2013-01-01 19:00:00 6404
1        1            2013-01-01 00:00:00 4608
2        1            2013-01-01 00:00:00 4579
3        1            2013-01-01 13:00:00 4516
4        1            2013-01-01 17:00:00 5632
...      ...          ...
122,134  1            2022-12-31 05:00:00 10554
122,135  1            2022-12-31 06:00:00 6947
122,136  1            2022-12-31 06:00:00 4006
122,137  1            2022-12-31 06:30:00 10785
122,138  1            2022-12-31 08:30:00 6212

In [12]:
#group by unir and sum

acci_vaex = acci_vaex.groupby('unir', agg={'accidente':'sum'})

acci_vaex

#        unir                       accidente
0        2013-01-02 12:00:00 6928   1
1        2013-01-04 14:00:00 10002  1
2        2013-01-08 10:00:00 4452   1
3        2013-01-10 20:00:00 9864   1
4        2013-01-10 08:00:00 4032   1
...      ...                        ...
118,511  2019-12-14 15:00:00 4033   1
118,512  2019-12-14 01:00:00 9981   1
118,513  2019-12-16 11:00:00 4170   1
118,514  2019-12-19 20:00:00 5893   1
118,515  2019-12-19 20:30:00 10889  1

In [13]:
acci_vaex.accidente.value_counts()

1    114910
2      3596
4         7
3         3
dtype: int64

In [23]:
acci_vaex.info()

In [14]:
#read traf_hist

traf_geo_meteo = vaex.open('../../TRAFICO/traf_hist.hdf5')

traf_geo_meteo

#            idelem    fecha_full           intensidad    ocupacion    carga    prec    velmedia
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0      0,7     3,3
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0     0,7     3,3
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0     0,7     3,3
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0     0,7     3,3
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0     0,7     3,3
...          ...       ...                  ...           ...          ...      ...     ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0      0,1     0,3
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0      0,1     0,3
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0      0,1     0,3
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0      0,1     0,3
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0      0,1     0,3

In [15]:
#join fecha_full and idelem, it is a vaex dataframe

traf_geo_meteo.info()

In [16]:
#transform idelem to str

traf_geo_meteo['idelem'] = traf_geo_meteo['idelem'].astype('string')

traf_geo_meteo.info()

In [19]:
#concatenate fecha_full and idelem

traf_geo_meteo['unir'] = traf_geo_meteo['fecha_full'] + ' ' + traf_geo_meteo['idelem']

traf_geo_meteo

#            idelem    fecha_full           intensidad    ocupacion    carga    prec    velmedia    unir
0            3564      2013-01-20 20:30:00  8.0           0.0          1.0      0,7     3,3         2013-01-20 20:30:00 3564
1            3882      2013-01-20 20:30:00  1164.0        4.0          22.0     0,7     3,3         2013-01-20 20:30:00 3882
2            3883      2013-01-20 20:30:00  1143.0        4.0          22.0     0,7     3,3         2013-01-20 20:30:00 3883
3            3884      2013-01-20 20:30:00  958.0         3.0          18.0     0,7     3,3         2013-01-20 20:30:00 3884
4            3885      2013-01-20 20:30:00  1028.0        4.0          20.0     0,7     3,3         2013-01-20 20:30:00 3885
...          ...       ...                  ...           ...          ...      ...     ...         ...
563,682,229  11058     2022-12-31 21:30:00  259.0         0.0          8.0      0,1     0,3         2022-12-31 21:30:00 11058
563,682,230  11058     2022-12-31 22:00:00  125.0         0.0          3.0      0,1     0,3         2022-12-31 22:00:00 11058
563,682,231  11058     2022-12-31 22:30:00  68.0          0.0          1.0      0,1     0,3         2022-12-31 22:30:00 11058
563,682,232  11058     2022-12-31 23:00:00  66.0          0.0          1.0      0,1     0,3         2022-12-31 23:00:00 11058
563,682,233  11058     2022-12-31 23:30:00  42.0          0.0          0.0      0,1     0,3         2022-12-31 23:30:00 11058

In [28]:
#join traf_geo_meteo and acci

#traf_geo_meteo_acci = traf_geo_meteo.join(acci_vaex, on='unir', how='right', lsuffix='_left', rsuffix='_right')

#traf_geo_meteo_acci

In [ ]:
#traf_geo_meteo_acci.accidente.value_counts()

In [25]:
#save to hdf5

traf_geo_meteo.export_hdf5('../../TRAFICO/traf_hist_unir.hdf5')

In [26]:
#read traf_hist_unir

traf_geo_meteo = vaex.open('../../TRAFICO/traf_hist_unir.hdf5')

In [29]:
traf_geo_meteo.info()

In [34]:
#search for unir in acci_vaex that are not in traf_geo_meteo

acci_vaex['unir'].values

traf_geo_meteo['unir'].values

diff = np.setdiff1d(acci_vaex['unir'].values, traf_geo_meteo['unir'].values)

In [ ]:
diff

In [191]:
#get uniques in unir in acci_vaex

acci_vaex['unir'].unique()

['2013-01-02 12:00:00 6928',
 '2013-01-04 14:00:00 10002',
 '2013-01-08 10:00:00 4452',
 '2013-01-10 20:00:00 9864',
 '2013-01-10 08:00:00 4032',
 '2013-01-11 00:30:00 10787',
 '2013-01-11 19:00:00 3892',
 '2013-01-17 08:00:00 5568',
 '2013-01-24 12:00:00 3945',
 '2013-01-25 15:30:00 3614',
 '2013-01-28 12:00:00 6029',
 '2013-02-07 15:00:00 7038',
 '2013-02-08 16:00:00 10018',
 '2013-02-08 02:30:00 4785',
 '2013-02-10 19:30:00 4654',
 '2013-02-16 08:30:00 5284',
 '2013-02-18 21:30:00 4730',
 '2013-02-25 19:00:00 6037',
 '2013-03-01 20:00:00 3471',
 '2013-03-01 17:30:00 4756',
 '2013-03-06 13:00:00 4170',
 '2013-03-07 13:30:00 4310',
 '2013-03-12 13:00:00 10101',
 '2013-03-14 14:30:00 4409',
 '2013-03-14 13:00:00 4892',
 '2013-03-16 00:30:00 4433',
 '2013-03-21 09:30:00 3745',
 '2013-03-23 13:30:00 10083',
 '2013-03-23 01:30:00 10082',
 '2013-03-24 21:30:00 6402',
 '2013-03-24 03:00:00 4041',
 '2013-03-27 18:30:00 10787',
 '2013-03-29 19:00:00 4173',
 '2013-04-04 15:30:00 7030',
 '2013-04-06 19:30:00 4028',
 '2013-04-08 21:30:00 10822',
 '2013-04-12 21:30:00 4406',
 '2013-04-15 18:00:00 6604',
 '2013-04-16 14:00:00 5530',
 '2013-04-18 15:30:00 4955',
 '2013-04-21 22:30:00 6322',
 '2013-04-24 19:30:00 6398',
 '2013-04-29 22:00:00 4790',
 '2013-05-01 19:30:00 6404',
 '2013-05-01 11:30:00 4217',
 '2013-05-06 12:30:00 10221',
 '2013-05-09 20:30:00 5625',
 '2013-05-14 21:30:00 3910',
 '2013-05-14 19:00:00 3949',
 '2013-05-17 07:00:00 9895',
 '2013-05-20 16:00:00 6533',
 '2013-05-20 21:00:00 4757',
 '2013-05-24 18:30:00 6952',
 '2013-05-25 21:00:00 6637',
 '2013-05-31 14:00:00 6928',
 '2013-05-31 11:00:00 4110',
 '2013-06-12 22:30:00 5095',
 '2013-06-16 22:30:00 3992',
 '2013-06-17 14:00:00 6341',
 '2013-06-28 15:00:00 4144',
 '2013-07-04 22:30:00 5592',
 '2013-07-05 13:30:00 10861',
 '2013-07-05 10:30:00 6979',
 '2013-07-05 14:00:00 4006',
 '2013-07-07 03:00:00 6950',
 '2013-07-08 11:30:00 4782',
 '2013-07-10 20:30:00 4868',
 '2013-07-10 13:30:00 5825',
 '2013-07-15 17:30:00 10781',
 '2013-07-17 11:00:00 6569',
 '2013-07-18 09:30:00 4476',
 '2013-07-19 15:00:00 6493',
 '2013-07-21 23:00:00 5764',
 '2013-07-22 20:00:00 5511',
 '2013-07-24 20:00:00 4424',
 '2013-07-26 20:30:00 3512',
 '2013-07-26 13:00:00 5171',
 '2013-07-28 18:30:00 6147',
 '2013-07-28 20:30:00 5361',
 '2013-07-31 15:00:00 3456',
 '2013-08-02 19:00:00 6553',
 '2013-08-02 09:30:00 3969',
 '2013-08-03 14:30:00 3944',
 '2013-08-05 18:30:00 10704',
 '2013-08-06 06:00:00 6492',
 '2013-08-07 23:30:00 10869',
 '2013-08-07 11:00:00 5566',
 '2013-08-09 13:00:00 3902',
 '2013-08-11 16:30:00 6535',
 '2013-08-12 13:00:00 3847',
 '2013-08-13 21:00:00 6552',
 '2013-08-13 08:30:00 4011',
 '2013-08-18 22:30:00 5271',
 '2013-08-25 01:30:00 7133',
 '2013-09-01 10:00:00 5810',
 '2013-09-01 09:30:00 11014',
 '2013-09-02 06:00:00 4347',
 '2013-09-07 18:30:00 3734',
 '2013-09-07 20:30:00 5797',
 '2013-09-08 11:00:00 11017',
 '2013-09-11 20:00:00 3849',
 '2013-09-14 12:00:00 4145',
 '2013-09-17 11:00:00 9908',
 '2013-09-17 07:30:00 4488',
 '2013-09-18 14:30:00 7020',
 '2013-09-18 09:30:00 4203',
 '2013-09-24 13:00:00 5584',
 '2013-09-26 11:30:00 6548',
 '2013-09-26 13:30:00 4009',
 '2013-10-02 00:30:00 5499',
 '2013-10-06 11:30:00 9963',
 '2013-10-07 12:00:00 10050',
 '2013-10-08 10:30:00 4693',
 '2013-10-10 12:00:00 10498',
 '2013-10-15 13:00:00 6345',
 '2013-10-17 19:30:00 6928',
 '2013-10-17 18:00:00 3851',
 '2013-10-23 17:30:00 4239',
 '2013-10-24 10:30:00 7081',
 '2013-10-24 13:00:00 3908',
 '2013-10-26 13:00:00 4455',
 '2013-10-28 15:30:00 10512',
 '2013-10-28 15:00:00 6358',
 '2013-11-04 20:00:00 3891',
 '2013-11-06 18:30:00 5170',
 '2013-11-11 09:30:00 3798',
 '2013-11-14 14:00:00 5170',
 '2013-11-14 19:30:00 3808',
 '2013-11-18 10:00:00 5703',
 '2013-11-18 10:30:00 4352',
 '2013-11-18 11:30:00 4360',
 '2013-11-22 14:00:00 6688',
 '2013-11-23 11:30:00 5084',
 '2013-11-24 17:00:00 10224',
 '2013-11-28 15:30:00 5458',
 '2013-11-28 11:30:00 3845',
 '2013-11-29 14:30:00 6048',
 '2013-12-02 13:30:00 9945',
 '2013-12-07 13:30:00 3793',
 '2013-12-11 19:30:00 5802',
 '2013-12-13 09:00:00 3998',
 '2013-12-14 19:00:00 7057',
 '2013-12-20 09:00:00 4434',
 '2013-12-21 07:30:00 4199',
 '2013-12-22 18:30:00 5814',
 '2013-12-23 14:30:00 3862',
 '2013-12-26 18:30:00 6125',
 '2013-12-28 12:00:00 9969',
 '2013-12-29 15:30:00 1003',
 '2013-12-29 20:00:00 5972',
 '2014-01-05 17:30:00 5602',
 '2014-01-07 15:00:00 5948',
 '2014-01-11 12:00:00 5849',
 '2014-01-12 16:30:00 3845',
 '2014-01-13 14:30:00 5350',
 '2014-01-13 23:30:00 10679',
 '2014-01-14 20:30:00 6702',
 '2014-01-18 14:00:00 5622',
 '2014-01-18 12:30:00 4132',
 '2014-01-23 18:30:00 5728',
 '2014-01-26 11:30:00 5159',
 '2014-01-27 21:30:00 5197',
 '2014-02-01 01:30:00 11023',
 '2014-02-07 15:30:00 4868',
 '2014-02-10 16:00:00 4033',
 '2014-02-12 17:00:00 3749',
 '2014-02-12 20:00:00 4676',
 '2014-02-15 03:00:00 10491',
 '2014-02-20 08:30:00 3787',
 '2014-02-24 07:00:00 1002',
 '2014-02-27 22:00:00 4447',
 '2014-03-01 15:00:00 6350',
 '2014-03-05 05:30:00 5474',
 '2014-03-06 08:00:00 4469',
 '2014-03-06 16:30:00 4049',
 '2014-03-06 09:30:00 4197',
 '2014-03-11 12:30:00 10987',
 '2014-03-11 21:00:00 4118',
 '2014-03-11 21:30:00 10116',
 '2014-03-12 11:30:00 5912',
 '2014-03-13 15:00:00 4199',
 '2014-03-18 20:30:00 4557',
 '2014-03-27 15:30:00 3998',
 '2014-03-28 23:30:00 5402',
 '2014-03-31 17:00:00 3798',
 '2014-04-01 16:00:00 4608',
 '2014-04-04 03:00:00 6894',
 '2014-04-09 09:00:00 5588',
 '2014-04-09 14:30:00 4113',
 '2014-04-22 12:00:00 5480',
 '2014-04-24 08:30:00 3851',
 '2014-05-02 09:00:00 3977',
 '2014-05-03 14:30:00 4246',
 '2014-05-06 12:30:00 4483',
 '2014-05-09 13:00:00 3876',
 '2014-05-15 21:30:00 10653',
 '2014-05-15 14:30:00 4706',
 '2014-05-15 15:00:00 3950',
 '2014-05-22 12:00:00 7070',
 '2014-05-27 14:30:00 5508',
 '2014-05-29 15:30:00 3459',
 '2014-05-31 15:30:00 4196',
 '2014-06-03 16:30:00 3860',
 '2014-06-11 09:30:00 5812',
 '2014-06-12 16:00:00 4453',
 '2014-06-16 16:00:00 4798',
 '2014-06-25 15:30:00 3704',
 '2014-06-28 09:30:00 4428',
 '2014-06-30 14:30:00 6553',
 '2014-07-04 10:30:00 4441',
 '2014-07-18 16:00:00 5554',
 '2014-07-21 14:00:00 5552',
 '2014-07-21 21:30:00 5180',
 '2014-07-21 12:00:00 6898',
 '2014-07-22 17:30:00 3975',
 '2014-07-26 22:00:00 9864',
 '2014-07-28 23:30:00 5868',
 '2014-07-29 21:30:00 3465',
 '2014-07-30 12:00:00 6359',
 '2014-07-31 18:00:00 5689',
 '2014-08-01 14:30:00 3930',
 '2014-08-01 08:30:00 10809',
 '2014-08-09 11:30:00 3407',
 '2014-08-09 13:30:00 4651',
 '2014-08-14 22:30:00 10421',
 '2014-08-18 17:30:00 6291',
 '2014-08-18 07:30:00 5488',
 '2014-08-19 17:30:00 5581',
 '2014-08-20 15:00:00 7030',
 '2014-08-21 21:30:00 10215',
 '2014-08-23 15:30:00 10159',
 '2014-08-24 09:00:00 7123',
 '2014-08-30 13:00:00 1006',
 '2014-09-03 13:00:00 10302',
 '2014-09-07 16:30:00 4730',
 '2014-09-08 20:00:00 6555',
 '2014-09-09 14:30:00 6192',
 '2014-09-14 00:00:00 10715',
 '2014-09-15 10:00:00 10034',
 '2014-09-19 19:30:00 4077',
 '2014-09-20 17:00:00 10257',
 '2014-09-24 20:00:00 6399',
 '2014-09-27 22:30:00 3741',
 '2014-09-29 08:00:00 4659',
 '2014-10-07 13:00:00 4190',
 '2014-10-10 18:30:00 10861',
 '2014-10-11 17:00:00 9985',
 '2014-10-13 00:30:00 10386',
 '2014-10-14 10:00:00 10101',
 '2014-10-16 18:00:00 9855',
 '2014-10-23 09:00:00 4353',
 '2014-10-25 15:00:00 4295',
 '2014-10-28 20:30:00 5652',
 '2014-10-29 20:00:00 4031',
 '2014-10-30 15:00:00 5041',
 '2014-11-01 01:00:00 4215',
 '2014-11-01 09:30:00 4669',
 '2014-11-03 16:00:00 4868',
 '2014-11-10 22:30:00 5380',
 '2014-11-11 14:30:00 3463',
 '2014-11-12 16:30:00 10635',
 '2014-11-12 12:00:00 6019',
 '2014-11-13 20:00:00 3931',
 '2014-11-14 13:30:00 4219',
 '2014-11-17 22:00:00 9979',
 '2014-11-19 16:00:00 4421',
 '2014-11-20 18:00:00 5271',
 '2014-11-21 09:30:00 5581',
 '2014-11-27 14:30:00 5761',
 '2014-11-27 19:30:00 3562',
 '2014-11-28 18:30:00 7074',
 '2014-12-03 13:30:00 5165',
 '2014-12-16 11:30:00 10217',
 '2014-12-22 20:30:00 3849',
 '2014-12-23 18:00:00 5365',
 '2014-12-28 08:00:00 4009',
 '2015-01-03 13:00:00 6605',
 '2015-01-06 15:00:00 10634',
 '2015-01-09 09:30:00 6623',
 '2015-01-10 14:00:00 4589',
 '2015-01-12 08:30:00 4411',
 '2015-01-16 14:00:00 6637',
 '2015-01-17 21:00:00 4407',
 '2015-01-19 12:00:00 5581',
 '2015-01-21 12:30:00 3499',
 '2015-01-25 12:30:00 4955',
 '2015-01-25 16:00:00 3726',
 '2015-01-29 12:00:00 5711',
 '2015-01-29 18:00:00 3834',
 '2015-02-02 15:00:00 7020',
 '2015-02-04 18:00:00 10595',
 '2015-02-06 13:00:00 6003',
 '2015-02-06 08:00:00 10730',
 '2015-02-16 21:00:00 4577',
 '2015-02-17 14:00:00 10634',
 '2015-02-22 08:00:00 6140',
 '2015-02-23 18:30:00 6552',
 '2015-02-25 14:00:00 9950',
 '2015-02-26 14:00:00 4727',
 '2015-02-28 14:30:00 9994',
 '2015-03-03 19:30:00 10852',
 '2015-03-06 01:30:00 3922',
 '2015-03-11 09:30:00 3456',
 '2015-03-15 09:00:00 3840',
 '2015-03-16 11:00:00 6135',
 '2015-03-18 22:30:00 10986',
 '2015-03-21 00:00:00 4708',
 '2015-03-26 11:30:00 4436',
 '2015-03-28 20:00:00 5146',
 '2015-04-12 19:00:00 3432',
 '2015-04-15 23:30:00 6555',
 '2015-04-16 08:30:00 4733',
 '2015-04-30 15:30:00 10123',
 '2015-04-30 20:30:00 4700',
 '2015-05-03 21:30:00 5402',
 '2015-05-03 14:00:00 4581',
 '2015-05-06 16:30:00 10685',
 '2015-05-07 21:30:00 5792',
 '2015-05-08 01:00:00 10907',
 '2015-05-11 00:00:00 3962',
 '2015-05-15 09:00:00 6526',
 '2015-05-21 16:00:00 7137',
 '2015-05-22 13:00:00 5904',
 '2015-05-25 11:00:00 10273',
 '2015-05-28 17:00:00 4101',
 '2015-06-03 17:00:00 11051',
 '2015-06-03 21:30:00 4035',
 '2015-06-07 11:30:00 9840',
 '2015-06-09 23:30:00 6950',
 '2015-06-11 14:00:00 6828',
 '2015-06-11 15:00:00 3886',
 '2015-06-14 02:30:00 4159',
 '2015-06-17 13:00:00 5901',
 '2015-06-17 01:30:00 10217',
 '2015-06-17 15:00:00 4197',
 '2015-06-18 15:30:00 3792',
 '2015-06-19 14:30:00 4838',
 '2015-06-20 23:30:00 4436',
 '2015-06-22 19:00:00 9994',
 '2015-06-22 16:30:00 4041',
 '2015-06-23 13:00:00 10663',
 '2015-06-23 18:30:00 4994',
 '2015-06-25 21:00:00 6469',
 '2015-07-01 13:00:00 4904',
 '2015-07-10 07:00:00 5135',
 '2015-07-13 08:00:00 10117',
 '2015-07-18 21:30:00 7091',
 '2015-07-22 15:30:00 5512',
 '2015-07-23 09:30:00 5439',
 '2015-07-23 12:30:00 6355',
 '2015-07-24 08:00:00 10818',
 '2015-07-27 13:00:00 6304',
 '2015-07-28 23:30:00 3562',
 '2015-07-31 16:00:00 10048',
 '2015-07-31 07:30:00 6033',
 '2015-08-02 17:00:00 5282',
 '2015-08-04 19:30:00 10968',
 '2015-08-06 09:00:00 10878',
 '2015-08-08 13:00:00 10833',
 '2015-08-09 16:30:00 10872',
 '2015-08-10 19:00:00 5380',
 '2015-08-19 20:30:00 11019',
 '2015-08-26 09:00:00 10861',
 '2015-08-27 23:00:00 5013',
 '2015-09-11 18:30:00 9883',
 '2015-09-12 16:00:00 4390',
 '2015-09-13 12:30:00 4211',
 '2015-09-14 15:00:00 4454',
 '2015-09-14 15:30:00 5489',
 '2015-09-15 18:00:00 5675',
 '2015-09-16 18:30:00 4641',
 '2015-09-17 10:00:00 4818',
 '2015-09-18 22:30:00 4219',
 '2015-09-20 03:00:00 6928',
 '2015-09-21 19:30:00 5467',
 '2015-09-21 09:00:00 3403',
 '2015-09-24 16:00:00 4379',
 '2015-09-25 21:30:00 3505',
 '2015-10-03 09:00:00 5551',
 '2015-10-04 15:00:00 6552',
 '2015-10-04 21:30:00 7139',
 '2015-10-07 09:30:00 6960',
 '2015-10-07 18:00:00 6163',
 '2015-10-14 17:30:00 5214',
 '2015-10-15 15:00:00 5348',
 '2015-10-18 19:00:00 5280',
 '2015-10-19 10:00:00 10835',
 '2015-10-20 12:30:00 10823',
 '2015-10-30 12:00:00 7120',
 '2015-11-01 12:30:00 6411',
 '2015-11-02 11:30:00 6394',
 '2015-11-03 18:00:00 9855',
 '2015-11-03 15:30:00 6311',
 '2015-11-04 18:00:00 5359',
 '2015-11-05 09:00:00 10442',
 '2015-11-08 17:00:00 4436',
 '2015-11-10 14:30:00 5443',
 '2015-11-14 12:00:00 4722',
 '2015-11-14 21:30:00 4439',
 '2015-11-19 14:30:00 6483',
 '2015-11-30 23:30:00 10603',
 '2015-12-02 14:30:00 6121',
 '2015-12-07 15:30:00 4099',
 '2015-12-13 13:30:00 4146',
 '2015-12-13 19:00:00 5380',
 '2015-12-19 08:00:00 5818',
 '2015-12-23 20:30:00 10801',
 '2015-12-25 22:30:00 9977',
 '2015-12-28 21:00:00 10217',
 '2015-12-29 14:30:00 10929',
 '2016-01-01 09:30:00 10861',
 '2016-01-07 13:30:00 10079',
 '2016-01-08 20:30:00 10061',
 '2016-01-12 16:00:00 5831',
 '2016-01-15 15:30:00 3885',
 '2016-01-22 15:00:00 5127',
 '2016-01-25 20:00:00 4088',
 '2016-01-26 19:00:00 5439',
 '2016-01-26 18:30:00 4643',
 '2016-01-27 22:30:00 6340',
 '2016-01-27 20:00:00 5629',
 '2016-02-03 15:30:00 5670',
 '2016-02-04 21:00:00 5271',
 '2016-02-07 14:30:00 3895',
 '2016-02-07 15:30:00 6895',
 '2016-02-09 12:00:00 5878',
 '2016-02-10 20:30:00 3892',
 '2016-02-11 15:00:00 4628',
 '2016-02-11 19:30:00 6498',
 '2016-02-12 16:00:00 10340',
 '2016-02-14 15:30:00 4574',
 '2016-02-15 14:30:00 10911',
 '2016-02-17 21:00:00 10284',
 '2016-02-18 16:30:00 5972',
 '2016-02-19 17:30:00 6669',
 '2016-02-19 09:00:00 4654',
 '2016-02-20 19:00:00 5029',
 '2016-02-22 21:00:00 5402',
 '2016-02-24 11:30:00 6928',
 '2016-02-24 23:30:00 4923',
 '2016-03-03 13:30:00 10132',
 '2016-03-03 16:00:00 6553',
 '2016-03-03 14:30:00 6688',
 '2016-03-03 15:00:00 4293',
 '2016-03-04 22:30:00 5764',
 '2016-03-05 17:30:00 4054',
 '2016-03-05 18:30:00 4187',
 '2016-03-06 08:30:00 6356',
 '2016-03-11 14:00:00 4048',
 '2016-03-17 14:30:00 5462',
 '2016-03-17 03:30:00 4454',
 '2016-03-18 22:30:00 11027',
 '2016-03-19 16:30:00 4454',
 '2016-03-19 04:30:00 3892',
 '2016-03-21 14:00:00 3718',
 '2016-03-24 00:30:00 5443',
 '2016-03-27 18:00:00 3734',
 '2016-03-29 07:00:00 3501',
 '2016-03-30 08:00:00 4565',
 '2016-04-01 15:00:00 6384',
 '2016-04-02 11:30:00 3837',
 '2016-04-03 16:30:00 6319',
 '2016-04-06 11:00:00 4165',
 '2016-04-06 18:30:00 10355',
 '2016-04-07 22:00:00 5402',
 '2016-04-08 17:30:00 9839',
 '2016-04-08 08:30:00 6319',
 '2016-04-11 19:30:00 9945',
 '2016-04-11 19:30:00 3864',
 '2016-04-13 11:00:00 10193',
 '2016-04-13 14:30:00 4428',
 '2016-04-15 00:00:00 5968',
 '2016-04-20 07:30:00 3801',
 '2016-04-21 18:00:00 3632',
 '2016-04-23 19:00:00 10136',
 '2016-04-29 23:00:00 4200',
 '2016-04-30 13:30:00 10195',
 '2016-05-02 20:00:00 6582',
 '2016-05-02 15:00:00 3974',
 '2016-05-03 22:30:00 6830',
 '2016-05-04 11:30:00 4415',
 '2016-05-06 20:30:00 4945',
 '2016-05-07 14:00:00 4775',
 '2016-05-07 16:30:00 3889',
 '2016-05-08 09:00:00 4385',
 '2016-05-10 18:00:00 10426',
 '2016-05-10 09:00:00 5118',
 '2016-05-12 13:30:00 6928',
 '2016-05-12 09:30:00 5290',
 '2016-05-17 21:30:00 4579',
 '2016-05-17 21:30:00 10819',
 '2016-05-19 09:30:00 5073',
 '2016-05-27 15:00:00 4356',
 '2016-05-31 08:00:00 5309',
 '2016-06-07 17:30:00 3674',
 '2016-06-11 17:30:00 3572',
 '2016-06-14 18:00:00 6303',
 '2016-06-15 20:00:00 5609',
 '2016-06-16 14:00:00 10724',
 '2016-06-21 22:00:00 3815',
 '2016-06-22 18:30:00 10355',
 '2016-06-24 20:00:00 4945',
 '2016-06-30 11:30:00 10018',
 '2016-07-03 12:00:00 3587',
 '2016-07-03 07:30:00 10889',
 '2016-07-06 15:30:00 5867',
 '2016-07-10 16:30:00 3951',
 '2016-07-13 16:30:00 4391',
 '2016-07-13 00:00:00 6023',
 '2019-12-20 10:00:00 4809',
 '2019-12-20 20:30:00 10408',
 '2019-12-20 02:30:00 5004',
 '2019-12-21 17:00:00 10954',
 '2019-12-22 19:00:00 3485',
 '2019-12-22 19:30:00 6212',
 '2019-12-23 11:30:00 5155',
 '2019-12-23 17:00:00 5862',
 '2019-12-24 20:00:00 3425',
 '2019-12-26 09:00:00 5312',
 '2019-12-27 21:30:00 9978',
 '2019-12-28 20:00:00 5359',
 '2019-12-30 05:30:00 5222',
 '2020-01-01 16:30:00 6483',
 '2020-01-02 15:30:00 5471',
 '2020-01-02 17:30:00 4913',
 '2020-01-02 14:30:00 10193',
 '2020-01-02 16:30:00 6192',
 '2020-01-02 22:30:00 4711',
 '2020-01-03 21:30:00 5903',
 '2020-01-03 13:00:00 5976',
 '2020-01-06 11:30:00 4289',
 '2020-01-07 00:00:00 4618',
 '2020-01-08 13:30:00 6319',
 '2020-01-08 02:00:00 4945',
 '2020-01-09 23:30:00 4085',
 '2020-01-11 17:00:00 4747',
 '2020-01-11 11:30:00 9949',
 '2020-01-12 22:00:00 5501',
 '2020-01-12 12:00:00 4066',
 '2020-01-13 10:00:00 6768',
 '2020-01-13 08:30:00 7059',
 '2020-01-13 19:30:00 6883',
 '2020-01-14 17:00:00 4409',
 '2020-01-16 18:00:00 6826',
 '2020-01-17 16:00:00 4319',
 '2020-01-21 09:00:00 10775',
 '2020-01-22 02:30:00 3619',
 '2020-01-23 18:00:00 6325',
 '2020-01-27 11:30:00 10962',
 '2020-01-28 16:00:00 6203',
 '2020-01-30 12:00:00 9854',
 '2020-01-30 11:00:00 5510',
 '2020-01-30 10:00:00 3414',
 '2020-01-31 14:00:00 5512',
 '2020-01-31 15:00:00 5825',
 '2020-02-06 11:30:00 3524',
 '2020-02-06 15:00:00 5501',
 '2020-02-09 10:30:00 5629',
 '2020-02-09 12:00:00 4690',
 '2020-02-09 18:00:00 5985',
 '2020-02-10 11:30:00 4029',
 '2020-02-10 21:30:00 6222',
 '2020-02-11 19:30:00 10519',
 '2020-02-11 14:30:00 3578',
 '2020-02-12 11:30:00 6362',
 '2020-02-12 21:30:00 5207',
 '2020-02-14 11:30:00 4454',
 '2020-02-14 13:30:00 10172',
 '2020-02-16 02:00:00 4563',
 '2020-02-17 00:30:00 3524',
 '2020-02-19 13:30:00 6998',
 '2020-02-20 07:00:00 4170',
 '2020-02-21 15:30:00 4942',
 '2020-02-21 22:30:00 6032',
 '2020-02-25 20:30:00 6896',
 '2020-02-27 13:00:00 5474',
 '2020-02-27 17:00:00 9917',
 '2020-02-28 10:00:00 4251',
 '2020-02-29 21:00:00 5248',
 '2020-02-29 14:30:00 4013',
 '2020-02-29 19:30:00 3648',
 '2020-03-02 19:00:00 5911',
 '2020-03-03 00:30:00 6893',
 '2020-03-05 12:00:00 10191',
 '2020-03-06 01:00:00 4706',
 '2020-03-08 13:30:00 3967',
 '2020-03-09 18:00:00 6280',
 '2020-03-10 06:30:00 5106',
 '2020-03-10 22:30:00 9935',
 '2020-03-11 09:00:00 6582',
 '2020-03-11 18:00:00 5787',
 '2020-03-13 11:00:00 3670',
 '2020-03-13 18:30:00 5821',
 '2020-04-01 09:00:00 9839',
 '2020-04-01 19:30:00 5945',
 '2020-04-01 20:30:00 10787',
 '2020-04-02 09:30:00 6766',
 '2020-04-03 18:00:00 3693',
 '2020-04-03 01:00:00 4346',
 '2020-04-05 12:30:00 4590',
 '2020-04-05 10:30:00 3481',
 '2020-04-09 19:30:00 7091',
 '2020-04-10 23:30:00 5946',
 '2020-04-12 12:30:00 5272',
 '2020-04-12 14:00:00 4782',
 '2020-04-12 17:00:00 6789',
 '2020-04-12 20:30:00 5080',
 '2020-04-18 10:30:00 1034',
 '2020-04-20 14:00:00 5566',
 '2020-04-24 19:00:00 10929',
 '2020-04-24 20:30:00 10342',
 '2020-04-29 13:00:00 3546',
 '2020-05-01 16:30:00 5385',
 '2020-05-01 22:30:00 6439',
 '2020-05-02 12:00:00 3833',
 '2020-05-03 12:30:00 4766',
 '2020-05-07 07:30:00 3949',
 '2020-05-09 14:30:00 4195',
 '2020-05-09 01:30:00 6160',
 '2020-05-11 14:00:00 3930',
 '2020-05-12 13:30:00 5250',
 '2020-05-14 15:00:00 4393',
 '2020-05-15 09:00:00 5853',
 '2020-05-19 11:00:00 10461',
 '2020-05-20 07:30:00 4220',
 '2020-05-22 20:30:00 4904',
 '2020-05-29 18:00:00 4343',
 '2020-05-29 19:00:00 5714',
 '2020-05-29 12:00:00 4792',
 '2020-05-29 12:30:00 5912',
 '2020-05-29 18:30:00 5910',
 '2020-05-29 22:30:00 5784',
 '2020-05-30 02:30:00 10795',
 '2020-05-31 05:30:00 6099',
 '2020-06-02 15:00:00 10145',
 '2020-06-03 15:00:00 6497',
 '2020-06-06 21:00:00 6693',
 '2020-06-07 00:30:00 6216',
 '2020-06-07 07:30:00 10782',
 '2020-06-08 14:00:00 5401',
 '2020-06-08 12:00:00 3430',
 '2020-06-09 13:00:00 10388',
 '2020-06-10 19:00:00 5834',
 '2020-06-11 18:30:00 4557',
 '2020-06-11 23:30:00 5480',
 '2020-06-13 21:30:00 6467',
 '2020-06-17 01:00:00 6828',
 '2020-06-19 15:00:00 5866',
 '2020-06-25 20:30:00 3806',
 '2020-06-26 02:00:00 4452',
 '2020-06-27 02:00:00 4127',
 '2020-06-28 21:30:00 5316',
 '2020-06-29 08:30:00 10594',
 '2020-06-30 19:30:00 5626',
 '2020-06-30 22:30:00 4047',
 '2020-07-01 16:30:00 6759',
 '2020-07-02 19:00:00 5289',
 '2020-07-03 20:30:00 10939',
 '2020-07-03 07:30:00 5017',
 '2020-07-06 12:30:00 3849',
 '2020-07-11 19:30:00 5598',
 '2020-07-11 13:30:00 10170',
 '2020-07-13 20:30:00 6984',
 '2020-07-15 14:00:00 6214',
 '2020-07-16 11:30:00 6923',
 '2020-07-18 20:00:00 6483',
 '2020-07-19 11:00:00 6811',
 '2020-07-20 17:30:00 5031',
 '2020-07-21 06:30:00 5645',
 '2020-07-21 15:30:00 6789',
 '2020-07-21 16:30:00 6120',
 '2020-07-21 20:30:00 3654',
 '2020-07-22 11:30:00 10761',
 '2020-07-22 16:30:00 4965',
 '2020-07-28 12:00:00 10819',
 '2020-07-31 01:00:00 5493',
 '2020-08-01 22:00:00 4831',
 '2020-08-01 23:00:00 6276',
 '2020-08-03 07:00:00 5181',
 '2020-08-05 15:00:00 4749',
 '2020-08-07 05:00:00 10208',
 '2020-08-08 03:00:00 3889',
 '2020-08-12 10:00:00 9864',
 '2020-08-12 16:30:00 4828',
 '2020-08-19 14:30:00 5606',

In [192]:
#get uniques in unir in traf_geo_meteo

traf_geo_meteo['unir'].unique()

:

:

In [ ]:
#finde the difference between the two

diff = np.setdiff1d(acci_vaex['unir'].unique(), traf_geo_meteo['unir'].unique())

In [ ]:
diff

In [108]:
import tqdm

# define the name of the SQL table to create
table_name = 'trafico'

# define the chunk size for exporting the data to CSV
csv_chunk_size = 10000000

# define the chunk size for importing the data from CSV and exporting to SQL
sql_chunk_size = 10000000

# iterate over chunks of the Vaex dataframe and export each chunk to CSV
for i in tqdm.tqdm(range(0, len(traf_geo_meteo), csv_chunk_size)):
    # get the chunk of data as a Vaex dataframe
    chunk = traf_geo_meteo[i:i+csv_chunk_size]
    
    # export the chunk to a CSV file
    chunk.export_csv('chunk_{}.csv'.format(i), header=False, index=False)

# iterate over chunks of the CSV files and import each chunk into a Pandas dataframe and export to SQL
#for i in tqdm.tqdm(range(0, len(traf_geo_meteo), sql_chunk_size)):
    # read the chunk of data from the CSV file into a Pandas dataframe
    chunk_pandas = pd.read_csv('chunk_{}.csv'.format(i), header=None)
    
    # rename the columns of the Pandas dataframe to match the SQL table columns
    #chunk_pandas.columns = traf_geo_meteo.column_names()
    
    # export the chunk to the SQL database using the to_sql() method in Pandas
    chunk_pandas.to_sql(table_name, engine, if_exists='append', index=False, chunksize=sql_chunk_size)

  0%|          | 0/57 [00:18<?, ?it/s]

KeyboardInterrupt:

In [104]:
#get list of column names from vaex dataframe

traf_geo_meteo.column_names()

TypeError: 'list' object is not callable